# site
site:
    host: https://zhouzh1.github.io
    title: Daily Notes
    keywords: []
    description: Just Some Notes
    author: zhouzh1
    avatar: ''
    rssSize: 10
    pageSize: 10
    theme: default
    copyright: ''
# contact
contact:
    email: yourname@gmail.com
    github: https://www.github.com/yourname
